version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "code-adam-tracker"
        BUILD_ENV: "prod"
        DISTRIBUTION_ID: "E36PLPV7SFW43T"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}
    post_build:
         commands:
            - aws s3 cp dist/* s3://${S3_BUCKET} --recursive
            - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths /index.html /*
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
